/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Defs_constants.h"



const DefsConstants g_Defs_constants;

DefsConstants::DefsConstants() {
}



