/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Defs_CONSTANTS_H
#define Defs_CONSTANTS_H

#include "Defs_types.h"



class DefsConstants {
 public:
  DefsConstants();

};

extern const DefsConstants g_Defs_constants;



#endif
