/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef H2103_Host_Invoke_CONSTANTS_H
#define H2103_Host_Invoke_CONSTANTS_H

#include "H2103_Host_Invoke_types.h"

namespace H2103_Host_Invoke {

class H2103_Host_InvokeConstants {
 public:
  H2103_Host_InvokeConstants();

};

extern const H2103_Host_InvokeConstants g_H2103_Host_Invoke_constants;

} // namespace

#endif
