/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "H2103_Slave_Invoke_constants.h"

namespace H2103_Slave_Invoke {

const H2103_Slave_InvokeConstants g_H2103_Slave_Invoke_constants;

H2103_Slave_InvokeConstants::H2103_Slave_InvokeConstants() {
}

} // namespace

